version: '3.8'
services:
  app:
    container_name: maps-example
    image: maps-example:local
    volumes:
      - type: bind
        source: ./static
        target: /usr/share/nginx/html/static/
    ports:
      - '8000:8000'
